### ISSUE TITLE
Has your bus ticker died 

### ISSUE THREAD

**Issue by TomWhitwell** [ismailuddin/raspberrypi#4]
Hi, was playing with the bus ticker code (on a mac, not on a raspberry pi) and got lots of errors that pointed me towards this blog post: http://robinosborne.co.uk/2017/01/09/london-buses-use-tls1-2/
Wondering if it is still working for you, or if I need to try to rework TfLAPI.py for ssl queries. 
Thanks!

**Comment by ismailuddin** [comment]
Hi Tom, thanks for pointing this out! I think you may be right! Ill look into it today, and update the code! Thanks for bringing it to my attention!

**Comment by ismailuddin** [comment]
I've just tried it on my PC, and it seems to be working fine for me..Could you post the details of the errors you are getting?

**Comment by TomWhitwell** [comment]
I'm using a mac, with Python 2.7.10 

I ran through your code commenting out all the lcd stuff, and get this error (I did more poking about with test files which made me think the error was along these lines: http://stackoverflow.com/questions/34522211/error-urllib2-python-ssl-tlsv1-alert-internal-error-ssl-c590 ) 

```
Warranty-Voided:ldn-bus-ticker tom$ sudo python ldn-bus-ticker.py 75232
Password:
 
Initialising...
Fetching TfL bus
arrivals...
Unable to connect to Internet...
Traceback (most recent call last):
  File "ldn-bus-ticker.py", line 67, in <module>
    arrivalsList = fetchBusArrivals()
  File "ldn-bus-ticker.py", line 54, in fetchBusArrivals
    for entry in jsonObject:
UnboundLocalError: local variable 'jsonObject' referenced before assignment
Warranty-Voided:ldn-bus-ticker tom$ 

```

**Comment by ismailuddin** [comment]
Hmm, so I don't think its a TLS issue because I don't have the same problem. For some reason you are getting a `urllib2.URLError`. I'm not sure if the behaviour of the `urllib2` module is different on Mac..?
If it is, could you try this code and see what happens:
```python
import urrlib2
import ssl
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
naptanID = "490015048A"
data = urllib2.urlopen("https://api.tfl.gov.uk/StopPoint/" + "%s" % naptanID + "/arrivals", context=context)
data.read()
```
Python should print a JSON-style set of data, with all the bus arrivals at the station. If this works, then this is the fix needed.

**Comment by TomWhitwell** [comment]
I just updated everything and now well! Going to try to get this running on a PocketCHIP next...
